<?php defined('BLUDIT') or die('Bludit CMS.'); ?>
{
    "fyra-vagar-till-ett-friskare-matsystem": {
        "title": "Fyra v\u00e4gar till ett friskare matsystem",
        "description": "Utbildning, forskning, folkh\u00e4lsa och generationsansvar \u2013 fyra omr\u00e5den d\u00e4r Sverige kan b\u00f6rja bygga ett matsystem som g\u00f6r oss friska.",
        "username": "erik",
        "tags": [],
        "type": "published",
        "date": "2026-07-16 10:30:00",
        "dateModified": "",
        "allowComments": false,
        "position": 7,
        "coverImage": "",
        "md5file": "",
        "category": "mat-halsa",
        "uuid": "ad23ba7d87b672cb455ecd3d9af65b52",
        "parent": "",
        "template": "",
        "noindex": false,
        "nofollow": false,
        "noarchive": false
    },
    "beskedet-som-forde-mig-till-fjallet": {
        "title": "Beskedet som f\u00f6rde mig till fj\u00e4llet",
        "description": "I slutet av 90-talet fick jag ett besked som \u00e4ndrade allt. V\u00e4gen tillbaka gick genom en f\u00e4bod utan el och vatten.",
        "username": "erik",
        "tags": [],
        "type": "published",
        "date": "2026-07-16 08:00:00",
        "dateModified": "",
        "allowComments": false,
        "position": 6,
        "coverImage": "erik-kaffe.jpg",
        "md5file": "",
        "category": "personligt",
        "uuid": "a5883e5a22eb745c4452f2dd1d082381",
        "parent": "",
        "template": "",
        "noindex": false,
        "nofollow": false,
        "noarchive": false
    },
    "friska-jorden-angar-oss-alla": {
        "title": "Varf\u00f6r den friska jorden ang\u00e5r oss alla",
        "description": "Matens kvalitet b\u00f6rjar under v\u00e5ra f\u00f6tter \u2013 i jorden. Om sambandet mellan mark, djur och v\u00e5r h\u00e4lsa.",
        "username": "erik",
        "tags": [],
        "type": "published",
        "date": "2026-07-10 08:15:00",
        "dateModified": "",
        "allowComments": false,
        "position": 1,
        "coverImage": "",
        "md5file": "",
        "category": "mat-halsa",
        "uuid": "cdb2c2a355d38085c6614a8cf877f8b3",
        "parent": "",
        "template": "",
        "noindex": false,
        "nofollow": false,
        "noarchive": false
    },
    "levande-gard-mer-an-produktion": {
        "title": "En levande g\u00e5rd \u00e4r mer \u00e4n produktion",
        "description": "En g\u00e5rd r\u00e4knas i liter och hektar \u2013 men b\u00e4r kunskap, beredskap och gemenskap som inte g\u00e5r att v\u00e4ga.",
        "username": "erik",
        "tags": [],
        "type": "published",
        "date": "2026-07-03 07:40:00",
        "dateModified": "",
        "allowComments": false,
        "position": 2,
        "coverImage": "",
        "md5file": "",
        "category": "landsbygd",
        "uuid": "bdc1d43cbe73435d4937fb7ee31445cb",
        "parent": "",
        "template": "",
        "noindex": false,
        "nofollow": false,
        "noarchive": false
    },
    "varfor-jag-inte-slarvar": {
        "title": "Varf\u00f6r jag inte slarvar",
        "description": "Kvalitet \u00e4r inget man skriver p\u00e5 en etikett. Det \u00e4r ett s\u00e4tt att arbeta \u2013 varje morgon, n\u00e4r ingen ser.",
        "username": "erik",
        "tags": [],
        "type": "published",
        "date": "2026-06-24 06:30:00",
        "dateModified": "",
        "allowComments": false,
        "position": 3,
        "coverImage": "terje-pa-marknad.jpg",
        "md5file": "",
        "category": "personligt",
        "uuid": "d6d2691ca5366fe9a526ea5dddfbad55",
        "parent": "",
        "template": "",
        "noindex": false,
        "nofollow": false,
        "noarchive": false
    },
    "beredskap-borjar-i-jorden": {
        "title": "Beredskap b\u00f6rjar i jorden",
        "description": "Ett land som inte kan producera sin egen mat \u00e4r s\u00e5rbart. Om varf\u00f6r beredskap odlas fram, \u00e5r f\u00f6r \u00e5r.",
        "username": "erik",
        "tags": [],
        "type": "published",
        "date": "2026-06-15 09:05:00",
        "dateModified": "",
        "allowComments": false,
        "position": 4,
        "coverImage": "",
        "md5file": "",
        "category": "beredskap",
        "uuid": "a7cef98a00e448dc305d1755865f585c",
        "parent": "",
        "template": "",
        "noindex": false,
        "nofollow": false,
        "noarchive": false
    },
    "fran-lot-till-riksdagen": {
        "title": "Fr\u00e5n L\u00f6t till en plats i samtalet",
        "description": "Varf\u00f6r jag v\u00e4ljer att ta plats d\u00e4r besluten fattas \u2013 utan att sl\u00e4ppa arbetet p\u00e5 g\u00e5rden.",
        "username": "erik",
        "tags": [],
        "type": "published",
        "date": "2026-06-05 18:20:00",
        "dateModified": "",
        "allowComments": false,
        "position": 5,
        "coverImage": "",
        "md5file": "",
        "category": "personligt",
        "uuid": "1f198a7424bfa86693d023800d771954",
        "parent": "",
        "template": "",
        "noindex": false,
        "nofollow": false,
        "noarchive": false
    },
    "kontakt": {
        "title": "Kontakt",
        "description": "Kontakta Terje Erik \u2013 mejeriet i L\u00f6t, \u00d6sterg\u00f6tland.",
        "username": "erik",
        "tags": [],
        "type": "static",
        "date": "2026-06-01 10:05:00",
        "dateModified": "",
        "allowComments": false,
        "position": 2,
        "coverImage": "",
        "md5file": "",
        "category": "general",
        "uuid": "c5057825415fe331a0f550bd582ba6d3",
        "parent": "",
        "template": "",
        "noindex": false,
        "nofollow": false,
        "noarchive": false
    },
    "om": {
        "title": "Om Terje Erik",
        "description": "Om Terje Erik \u2013 g\u00e5rdsmejerist i L\u00f6t, \u00d6sterg\u00f6tland, som skriver om mat, mark och h\u00e4lsa.",
        "username": "erik",
        "tags": [],
        "type": "static",
        "date": "2026-06-01 10:00:00",
        "dateModified": "",
        "allowComments": false,
        "position": 1,
        "coverImage": "erik-kaffe.jpg",
        "md5file": "",
        "category": "general",
        "uuid": "b3ccd3e6afc574ae683a08a9962682a7",
        "parent": "",
        "template": "",
        "noindex": false,
        "nofollow": false,
        "noarchive": false
    }
}