<?php defined('BLUDIT') or die('Bludit CMS.'); ?>
{
    "title": "Terje Erik",
    "slogan": "Bondf\u00f6rnuft",
    "description": "Terje Erik, riksdagskandidat f\u00f6r Socialdemokraterna i \u00d6sterg\u00f6tland, skriver fr\u00e5n g\u00e5rdsmejeriet i L\u00f6t om mat, h\u00e4lsa, landsbygd och beredskap.",
    "footer": "Fr\u00e5n L\u00f6t i \u00d6sterg\u00f6tland",
    "itemsPerPage": 4,
    "language": "sv_SE",
    "locale": "sv, sv_SE",
    "timezone": "Europe\/Stockholm",
    "theme": "terje",
    "adminTheme": "booty",
    "homepage": "",
    "pageNotFound": "",
    "uriPage": "\/",
    "uriTag": "\/tag\/",
    "uriCategory": "\/category\/",
    "uriBlog": "",
    "url": "http:\/\/terjeerik.test",
    "emailFrom": "no-reply@terjeerik.se",
    "orderBy": "date",
    "currentBuild": 20260207,
    "twitter": "",
    "facebook": "",
    "codepen": "",
    "github": "",
    "instagram": "",
    "gitlab": "",
    "linkedin": "",
    "xing": "",
    "telegram": "",
    "dateFormat": "j F Y",
    "extremeFriendly": true,
    "autosaveInterval": 2,
    "titleFormatHomepage": "{{site-title}} \u2013 {{site-slogan}}",
    "titleFormatPages": "{{page-title}} | {{site-title}}",
    "titleFormatCategory": "{{category-name}} | {{site-title}}",
    "titleFormatTag": "{{tag-name}} | {{site-title}}",
    "imageRestrict": true,
    "imageRelativeToAbsolute": false
}